server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: divyansh
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/